## This function will create a plot comparing Global Active Power in KW to frequency
mydata <- read.csv("household_power_consumption.txt", header = TRUE, sep = ";")
mydata1 <- subset(mydata, as.Date(mydata$Date,format='%d/%m/%Y') == as.Date('01/02/2007', format='%d/%m/%Y'))
mydata2 <- subset(mydata, as.Date(mydata$Date,format='%d/%m/%Y') == as.Date('02/02/2007', format='%d/%m/%Y'))
dtfrm <- data.frame()
dtfrm <- rbind(dtfrm, mydata1)
dtfrm <- rbind(dtfrm, mydata2)
dtfrm$Date <- as.character(dtfrm$Date)
dtfrm$Time <- as.character(dtfrm$Time)
dtfrm$NewDate <- strptime(dtfrm$Date, format = "%d/%m/%Y")
dtfrm$TxtDate <- format(dtfrm$NewDate, format = "%Y-%m-%d")
dtfrm$TxtTime <- format(dtfrm$Time, format = "%H:%M")
dtfrm$DateTime <- paste(dtfrm$TxtDate, dtfrm$TxtTime, sep = " ")
dtfrm$DateTime <- as.POSIXct(dtfrm$DateTime, format = "%Y-%m-%d %H:%M:%S")
png(filename = "plot2.png", width = 480, height = 480)
plot.new()
chartz <- plot(dtfrm$DateTime, as.numeric(as.character(dtfrm$Global_active_power)), ylab = "Global Active Power (kilowatts)", xlab = "", type = "l")
chartz
dev.off()